services:
  follow_your_name_images:
    image: nextimages
    container_name: next
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
    networks:
      - data_analytics

networks:
  data_analytics:
    external: true